server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orderService
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: 89e1284d-cd27-4f10-9961-3ff1297cb751
mybatis:
  type-aliases-package: com.pansky.order.entiy
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.pansky: debug
feign:
  client:
    config:
      default:
        connectTimeout: 1000 #单位毫秒
        readTimeout: 5000 #单位毫秒     //feign的调用时间，如果服务端响应超过这个时间，则远程调用失败，需要处理事务

userService:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则

#分布式事务Seata配置
seata:
  enabled: true
  tx-service-group: my_test_tx_group  # 定义事务分组
  # 开启数据源代理
  enable-auto-data-source-proxy: true
  # 数据源代理模式，使用AT模式

  service:
    vgroup-mapping:
      my_test_tx_group: default       # xxxx分组使用Seata的默认配置完成事务
    grouplist:
      default: localhost:8091     # 配置seata的地址和端口号(8091是默认端口号)


  # 配置中心，需要和 seata server 保持一致
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: 89e1284d-cd27-4f10-9961-3ff1297cb751
      group: DEFAULT_GROUP
      dataId: seataServer.properties
      username: nacos
      password: nacos

  # 注册中心，需要和 seata server 保持一致
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace: 89e1284d-cd27-4f10-9961-3ff1297cb751
      group: DEFAULT_GROUP
      cluster: default
      username: nacos
      password: nacos
  client:
    rm:
      lock:
        # 校验或占用全局锁重试间隔，单位ms
        retry-interval: 10
        # 校验或占用全局锁重试次数
        retry-times: 10
        # 分支事务与其它全局回滚事务冲突时锁策略,true，优先释放本地锁让回滚成功
        retry-policy-branch-rollback-on-conflict: true
    tm:
      # 一阶段全局提交结果上报TC重试次数
      commit-retry-count: 5
      # 一阶段全局回滚结果上报TC重试次数
      rollback-retry-count: 5
      # 分布式事物超时时间
#      default-global-transaction-timeout: 600000
      # 降级开关,false 不打开
      degrade-check: false
      degrade-check-period: 2000
      degrade-check-allow-times: 10
#      undo:
#        log-serialization: jackson
    log:
      exception-rate: 100