server:
  port: 8088
spring:
  application:
    name: sitService
  redis:
#    database: 0
#    host: 127.0.0.1
    host: 10.114.63.244
    port: 6379
    password:
logging:
  level:
    com.pansky: info
