server:
  port: 8080 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
      discovery:
        namespace: 89e1284d-cd27-4f10-9961-3ff1297cb751
    gateway:
      routes: # 网关路由配置
        - id: user-service # 路由id，自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://userService # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/** # 这个是按照路径匹配，只要以/user/开头就符合要求
        - id: order-service # 路由id，自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://orderService
          predicates:
            - Path=/order/**
            - After=2022-11-09T17:42:47.789-07:00[Asia/Shanghai]
          filters:
            - AddRequestHeader=CL-Request, Fo
            - AddResponseHeader=X-Response-Foo, Bar
  redis:
    host: 127.0.0.1
    port: 6379
#    password: pansky@123
    database: 0
key-resolver: '#{@apiKeyResolver}' # 通过spel表达式取 ioc容器中bean的值
redis-rate-limiter:
  replenishRate: 1  # 生成令牌的速度
  burstCapacity: 3  # 桶容量
