elasticsearch:
#  clusterName: es-cluster
  hosts: 192.168.137.10:9200
  #es用户名
  userName: elastic
  #es密码
  password: elastic
  # es 连接超时时间
  connectTimeOut: 1000
  # es socket 连接超时时间
  socketTimeOut: 30000
  # es 请求超时时间
  connectionRequestTimeOut: 500
  # es 最大连接数
  maxConnectNum: 100
  # es 每个路由的最大连接数
  maxConnectNumPerRoute: 100
  # es 请求方式
  scheme: http

