server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: thirdService
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: 89e1284d-cd27-4f10-9961-3ff1297cb751
logging:
  level:
    com.pansky: debug
feign:
  client:
    config:
      default:
        connectTimeout: 1000 #单位毫秒
        readTimeout: 5000 #单位毫秒     //feign的调用时间，如果服务端响应超过这个时间，则远程调用失败，需要处理事务